// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: src/proto/product-service.proto

package product

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProducService_Create_FullMethodName  = "/product.ProducService/Create"
	ProducService_FindAll_FullMethodName = "/product.ProducService/FindAll"
	ProducService_Find_FullMethodName    = "/product.ProducService/Find"
	ProducService_Update_FullMethodName  = "/product.ProducService/Update"
	ProducService_Delete_FullMethodName  = "/product.ProducService/Delete"
)

// ProducServiceClient is the client API for ProducService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ProductService provides operations for managing products.
type ProducServiceClient interface {
	// create a new product
	Create(ctx context.Context, in *ProductCreateRequest, opts ...grpc.CallOption) (*ProductResponse, error)
	// list all products
	FindAll(ctx context.Context, in *Product, opts ...grpc.CallOption) (*ProductCollection, error)
	// find one product by id
	Find(ctx context.Context, in *Product, opts ...grpc.CallOption) (*ProductResponse, error)
	// update a product
	Update(ctx context.Context, in *ProductUpdateRequest, opts ...grpc.CallOption) (*ProductResponse, error)
	// delete a product by id
	Delete(ctx context.Context, in *Product, opts ...grpc.CallOption) (*ProductResponse, error)
}

type producServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProducServiceClient(cc grpc.ClientConnInterface) ProducServiceClient {
	return &producServiceClient{cc}
}

func (c *producServiceClient) Create(ctx context.Context, in *ProductCreateRequest, opts ...grpc.CallOption) (*ProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProductResponse)
	err := c.cc.Invoke(ctx, ProducService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *producServiceClient) FindAll(ctx context.Context, in *Product, opts ...grpc.CallOption) (*ProductCollection, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProductCollection)
	err := c.cc.Invoke(ctx, ProducService_FindAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *producServiceClient) Find(ctx context.Context, in *Product, opts ...grpc.CallOption) (*ProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProductResponse)
	err := c.cc.Invoke(ctx, ProducService_Find_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *producServiceClient) Update(ctx context.Context, in *ProductUpdateRequest, opts ...grpc.CallOption) (*ProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProductResponse)
	err := c.cc.Invoke(ctx, ProducService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *producServiceClient) Delete(ctx context.Context, in *Product, opts ...grpc.CallOption) (*ProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProductResponse)
	err := c.cc.Invoke(ctx, ProducService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProducServiceServer is the server API for ProducService service.
// All implementations must embed UnimplementedProducServiceServer
// for forward compatibility.
//
// ProductService provides operations for managing products.
type ProducServiceServer interface {
	// create a new product
	Create(context.Context, *ProductCreateRequest) (*ProductResponse, error)
	// list all products
	FindAll(context.Context, *Product) (*ProductCollection, error)
	// find one product by id
	Find(context.Context, *Product) (*ProductResponse, error)
	// update a product
	Update(context.Context, *ProductUpdateRequest) (*ProductResponse, error)
	// delete a product by id
	Delete(context.Context, *Product) (*ProductResponse, error)
	mustEmbedUnimplementedProducServiceServer()
}

// UnimplementedProducServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProducServiceServer struct{}

func (UnimplementedProducServiceServer) Create(context.Context, *ProductCreateRequest) (*ProductResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedProducServiceServer) FindAll(context.Context, *Product) (*ProductCollection, error) {
	return nil, status.Error(codes.Unimplemented, "method FindAll not implemented")
}
func (UnimplementedProducServiceServer) Find(context.Context, *Product) (*ProductResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Find not implemented")
}
func (UnimplementedProducServiceServer) Update(context.Context, *ProductUpdateRequest) (*ProductResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedProducServiceServer) Delete(context.Context, *Product) (*ProductResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedProducServiceServer) mustEmbedUnimplementedProducServiceServer() {}
func (UnimplementedProducServiceServer) testEmbeddedByValue()                       {}

// UnsafeProducServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProducServiceServer will
// result in compilation errors.
type UnsafeProducServiceServer interface {
	mustEmbedUnimplementedProducServiceServer()
}

func RegisterProducServiceServer(s grpc.ServiceRegistrar, srv ProducServiceServer) {
	// If the following call panics, it indicates UnimplementedProducServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProducService_ServiceDesc, srv)
}

func _ProducService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProducServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProducService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProducServiceServer).Create(ctx, req.(*ProductCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProducService_FindAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Product)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProducServiceServer).FindAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProducService_FindAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProducServiceServer).FindAll(ctx, req.(*Product))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProducService_Find_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Product)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProducServiceServer).Find(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProducService_Find_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProducServiceServer).Find(ctx, req.(*Product))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProducService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProducServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProducService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProducServiceServer).Update(ctx, req.(*ProductUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProducService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Product)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProducServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProducService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProducServiceServer).Delete(ctx, req.(*Product))
	}
	return interceptor(ctx, in, info, handler)
}

// ProducService_ServiceDesc is the grpc.ServiceDesc for ProducService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProducService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "product.ProducService",
	HandlerType: (*ProducServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ProducService_Create_Handler,
		},
		{
			MethodName: "FindAll",
			Handler:    _ProducService_FindAll_Handler,
		},
		{
			MethodName: "Find",
			Handler:    _ProducService_Find_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ProducService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ProducService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/proto/product-service.proto",
}
