// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.3
// source: src/proto/shoppingcart-service.proto

package shoppingcart

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShoppingCartService_AddItem_FullMethodName = "/shoppingCart.ShoppingCartService/AddItem"
)

// ShoppingCartServiceClient is the client API for ShoppingCartService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShoppingCartServiceClient interface {
	AddItem(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CreateCartRequest, ShoppingCartTotal], error)
}

type shoppingCartServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShoppingCartServiceClient(cc grpc.ClientConnInterface) ShoppingCartServiceClient {
	return &shoppingCartServiceClient{cc}
}

func (c *shoppingCartServiceClient) AddItem(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CreateCartRequest, ShoppingCartTotal], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ShoppingCartService_ServiceDesc.Streams[0], ShoppingCartService_AddItem_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CreateCartRequest, ShoppingCartTotal]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ShoppingCartService_AddItemClient = grpc.BidiStreamingClient[CreateCartRequest, ShoppingCartTotal]

// ShoppingCartServiceServer is the server API for ShoppingCartService service.
// All implementations must embed UnimplementedShoppingCartServiceServer
// for forward compatibility.
type ShoppingCartServiceServer interface {
	AddItem(grpc.BidiStreamingServer[CreateCartRequest, ShoppingCartTotal]) error
	mustEmbedUnimplementedShoppingCartServiceServer()
}

// UnimplementedShoppingCartServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShoppingCartServiceServer struct{}

func (UnimplementedShoppingCartServiceServer) AddItem(grpc.BidiStreamingServer[CreateCartRequest, ShoppingCartTotal]) error {
	return status.Error(codes.Unimplemented, "method AddItem not implemented")
}
func (UnimplementedShoppingCartServiceServer) mustEmbedUnimplementedShoppingCartServiceServer() {}
func (UnimplementedShoppingCartServiceServer) testEmbeddedByValue()                             {}

// UnsafeShoppingCartServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShoppingCartServiceServer will
// result in compilation errors.
type UnsafeShoppingCartServiceServer interface {
	mustEmbedUnimplementedShoppingCartServiceServer()
}

func RegisterShoppingCartServiceServer(s grpc.ServiceRegistrar, srv ShoppingCartServiceServer) {
	// If the following call panics, it indicates UnimplementedShoppingCartServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShoppingCartService_ServiceDesc, srv)
}

func _ShoppingCartService_AddItem_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ShoppingCartServiceServer).AddItem(&grpc.GenericServerStream[CreateCartRequest, ShoppingCartTotal]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ShoppingCartService_AddItemServer = grpc.BidiStreamingServer[CreateCartRequest, ShoppingCartTotal]

// ShoppingCartService_ServiceDesc is the grpc.ServiceDesc for ShoppingCartService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShoppingCartService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shoppingCart.ShoppingCartService",
	HandlerType: (*ShoppingCartServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AddItem",
			Handler:       _ShoppingCartService_AddItem_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "src/proto/shoppingcart-service.proto",
}
