// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.3
// source: src/proto/shoppingcart-service.proto

package shoppingcart

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int32                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPrice     float64                `protobuf:"fixed64,3,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCartRequest) Reset() {
	*x = CreateCartRequest{}
	mi := &file_src_proto_shoppingcart_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCartRequest) ProtoMessage() {}

func (x *CreateCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_shoppingcart_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCartRequest.ProtoReflect.Descriptor instead.
func (*CreateCartRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_shoppingcart_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCartRequest) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CreateCartRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CreateCartRequest) GetUnitPrice() float64 {
	if x != nil {
		return x.UnitPrice
	}
	return 0
}

type ShoppingCartTotal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuantityItems int32                  `protobuf:"varint,1,opt,name=quantity_items,json=quantityItems,proto3" json:"quantity_items,omitempty"`
	TotalPrice    float64                `protobuf:"fixed64,2,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShoppingCartTotal) Reset() {
	*x = ShoppingCartTotal{}
	mi := &file_src_proto_shoppingcart_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShoppingCartTotal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShoppingCartTotal) ProtoMessage() {}

func (x *ShoppingCartTotal) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_shoppingcart_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShoppingCartTotal.ProtoReflect.Descriptor instead.
func (*ShoppingCartTotal) Descriptor() ([]byte, []int) {
	return file_src_proto_shoppingcart_service_proto_rawDescGZIP(), []int{1}
}

func (x *ShoppingCartTotal) GetQuantityItems() int32 {
	if x != nil {
		return x.QuantityItems
	}
	return 0
}

func (x *ShoppingCartTotal) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

var File_src_proto_shoppingcart_service_proto protoreflect.FileDescriptor

const file_src_proto_shoppingcart_service_proto_rawDesc = "" +
	"\n" +
	"$src/proto/shoppingcart-service.proto\x12\fshoppingCart\"m\n" +
	"\x11CreateCartRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x05R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12\x1d\n" +
	"\n" +
	"unit_price\x18\x03 \x01(\x01R\tunitPrice\"[\n" +
	"\x11ShoppingCartTotal\x12%\n" +
	"\x0equantity_items\x18\x01 \x01(\x05R\rquantityItems\x12\x1f\n" +
	"\vtotal_price\x18\x02 \x01(\x01R\n" +
	"totalPrice2f\n" +
	"\x13ShoppingCartService\x12O\n" +
	"\aAddItem\x12\x1f.shoppingCart.CreateCartRequest\x1a\x1f.shoppingCart.ShoppingCartTotal(\x010\x01B\x17Z\x15./src/pb/shoppingcartb\x06proto3"

var (
	file_src_proto_shoppingcart_service_proto_rawDescOnce sync.Once
	file_src_proto_shoppingcart_service_proto_rawDescData []byte
)

func file_src_proto_shoppingcart_service_proto_rawDescGZIP() []byte {
	file_src_proto_shoppingcart_service_proto_rawDescOnce.Do(func() {
		file_src_proto_shoppingcart_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_proto_shoppingcart_service_proto_rawDesc), len(file_src_proto_shoppingcart_service_proto_rawDesc)))
	})
	return file_src_proto_shoppingcart_service_proto_rawDescData
}

var file_src_proto_shoppingcart_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_src_proto_shoppingcart_service_proto_goTypes = []any{
	(*CreateCartRequest)(nil), // 0: shoppingCart.CreateCartRequest
	(*ShoppingCartTotal)(nil), // 1: shoppingCart.ShoppingCartTotal
}
var file_src_proto_shoppingcart_service_proto_depIdxs = []int32{
	0, // 0: shoppingCart.ShoppingCartService.AddItem:input_type -> shoppingCart.CreateCartRequest
	1, // 1: shoppingCart.ShoppingCartService.AddItem:output_type -> shoppingCart.ShoppingCartTotal
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_src_proto_shoppingcart_service_proto_init() }
func file_src_proto_shoppingcart_service_proto_init() {
	if File_src_proto_shoppingcart_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_proto_shoppingcart_service_proto_rawDesc), len(file_src_proto_shoppingcart_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_proto_shoppingcart_service_proto_goTypes,
		DependencyIndexes: file_src_proto_shoppingcart_service_proto_depIdxs,
		MessageInfos:      file_src_proto_shoppingcart_service_proto_msgTypes,
	}.Build()
	File_src_proto_shoppingcart_service_proto = out.File
	file_src_proto_shoppingcart_service_proto_goTypes = nil
	file_src_proto_shoppingcart_service_proto_depIdxs = nil
}
