// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.3
// source: src/proto/product-service.proto

package product

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListProductListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductListRequest) Reset() {
	*x = ListProductListRequest{}
	mi := &file_src_proto_product_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductListRequest) ProtoMessage() {}

func (x *ListProductListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_product_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductListRequest.ProtoReflect.Descriptor instead.
func (*ListProductListRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_product_service_proto_rawDescGZIP(), []int{0}
}

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_src_proto_product_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_product_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_src_proto_product_service_proto_rawDescGZIP(), []int{1}
}

func (x *Product) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Product) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type ProductListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductListResponse) Reset() {
	*x = ProductListResponse{}
	mi := &file_src_proto_product_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductListResponse) ProtoMessage() {}

func (x *ProductListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_product_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductListResponse.ProtoReflect.Descriptor instead.
func (*ProductListResponse) Descriptor() ([]byte, []int) {
	return file_src_proto_product_service_proto_rawDescGZIP(), []int{2}
}

func (x *ProductListResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

var File_src_proto_product_service_proto protoreflect.FileDescriptor

const file_src_proto_product_service_proto_rawDesc = "" +
	"\n" +
	"\x1fsrc/proto/product-service.proto\x12\aproduct\"\x18\n" +
	"\x16ListProductListRequest\"/\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"C\n" +
	"\x13ProductListResponse\x12,\n" +
	"\bproducts\x18\x01 \x03(\v2\x10.product.ProductR\bproducts2Z\n" +
	"\x0eProductService\x12H\n" +
	"\aFindAll\x12\x1f.product.ListProductListRequest\x1a\x1c.product.ProductListResponseB\x12Z\x10./src/pb/productb\x06proto3"

var (
	file_src_proto_product_service_proto_rawDescOnce sync.Once
	file_src_proto_product_service_proto_rawDescData []byte
)

func file_src_proto_product_service_proto_rawDescGZIP() []byte {
	file_src_proto_product_service_proto_rawDescOnce.Do(func() {
		file_src_proto_product_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_proto_product_service_proto_rawDesc), len(file_src_proto_product_service_proto_rawDesc)))
	})
	return file_src_proto_product_service_proto_rawDescData
}

var file_src_proto_product_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_src_proto_product_service_proto_goTypes = []any{
	(*ListProductListRequest)(nil), // 0: product.ListProductListRequest
	(*Product)(nil),                // 1: product.Product
	(*ProductListResponse)(nil),    // 2: product.ProductListResponse
}
var file_src_proto_product_service_proto_depIdxs = []int32{
	1, // 0: product.ProductListResponse.products:type_name -> product.Product
	0, // 1: product.ProductService.FindAll:input_type -> product.ListProductListRequest
	2, // 2: product.ProductService.FindAll:output_type -> product.ProductListResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_src_proto_product_service_proto_init() }
func file_src_proto_product_service_proto_init() {
	if File_src_proto_product_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_proto_product_service_proto_rawDesc), len(file_src_proto_product_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_proto_product_service_proto_goTypes,
		DependencyIndexes: file_src_proto_product_service_proto_depIdxs,
		MessageInfos:      file_src_proto_product_service_proto_msgTypes,
	}.Build()
	File_src_proto_product_service_proto = out.File
	file_src_proto_product_service_proto_goTypes = nil
	file_src_proto_product_service_proto_depIdxs = nil
}
