// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.3
// source: src/proto/cal-service.proto

package calc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CalService_Calc_FullMethodName = "/calc.CalService/Calc"
)

// CalServiceClient is the client API for CalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CalServiceClient interface {
	Calc(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Input, Output], error)
}

type calServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCalServiceClient(cc grpc.ClientConnInterface) CalServiceClient {
	return &calServiceClient{cc}
}

func (c *calServiceClient) Calc(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Input, Output], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CalService_ServiceDesc.Streams[0], CalService_Calc_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Input, Output]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CalService_CalcClient = grpc.ClientStreamingClient[Input, Output]

// CalServiceServer is the server API for CalService service.
// All implementations must embed UnimplementedCalServiceServer
// for forward compatibility.
type CalServiceServer interface {
	Calc(grpc.ClientStreamingServer[Input, Output]) error
	mustEmbedUnimplementedCalServiceServer()
}

// UnimplementedCalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCalServiceServer struct{}

func (UnimplementedCalServiceServer) Calc(grpc.ClientStreamingServer[Input, Output]) error {
	return status.Error(codes.Unimplemented, "method Calc not implemented")
}
func (UnimplementedCalServiceServer) mustEmbedUnimplementedCalServiceServer() {}
func (UnimplementedCalServiceServer) testEmbeddedByValue()                    {}

// UnsafeCalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CalServiceServer will
// result in compilation errors.
type UnsafeCalServiceServer interface {
	mustEmbedUnimplementedCalServiceServer()
}

func RegisterCalServiceServer(s grpc.ServiceRegistrar, srv CalServiceServer) {
	// If the following call panics, it indicates UnimplementedCalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CalService_ServiceDesc, srv)
}

func _CalService_Calc_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CalServiceServer).Calc(&grpc.GenericServerStream[Input, Output]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CalService_CalcServer = grpc.ClientStreamingServer[Input, Output]

// CalService_ServiceDesc is the grpc.ServiceDesc for CalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "calc.CalService",
	HandlerType: (*CalServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Calc",
			Handler:       _CalService_Calc_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "src/proto/cal-service.proto",
}
